language: android

jdk:
  - oraclejdk8

env:
    matrix:
      - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
      - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    global:
      - ADB_INSTALL_TIMEOUT=10    #Time out to 10 min

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

  #system images
  - sys-img-armeabi-v7a-android-19
  - sys-img-armeabi-v7a-android-21

licenses:
  - 'android-sdk-license-c81a61d9'
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'intel-android-extra-license.+'

sudo: false

before_install:
  - chmod +x gradlew
  - touch local.properties
  - pip install --user codecov

before_script:
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
  - ./gradlew --daemon build jacocoTestReport assembleAndroidTest
  - ./gradlew --daemon check
  - android-wait-for-emulator
  - adb devices   #Display list of devices
  - adb shell input keyevent 82 &
  - ./gradlew --daemon connectedCheck --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache