language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - sys-img-armeabi-v7a-android-26
    - extra-android-m2repository
    
env:
  matrix:
    - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a
    
before_install:
 - chmod +x gradlew
  
 # Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
 
script:
  - android list target
  - ./gradlew connectedAndroidTest
