language: android
jdk: oraclejdk8
sudo: true

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-21
    - android-26
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_script:
	-chmod +x gradlew

script: ./gradlew connectedAndroidTest

after_success:
	- bash <(curl -s https://codecov.io/bash)
